### ISSUE TITLE
Property definition does not show up in the concept

### ISSUE THREAD

**Issue by ReinhardWimmer** [BuildingSMART/IfcDoc#11]
Definition of different properties does not show up in the parameters window for the Properties.

Properties defined as:
- P_Enumeratedvalue
- P_Boundedvalue
- P_Listvalue
- P_Tablevalue
- P_Referencevalue
- Complex

Do not show up in the window "Parameters" (in the "Concept" tab of the concept "Property Sets for Objects")

**Comment by timchipman** [comment]
Fixed in V10.4 -- dropdown list switches between, templates added to support other property types
