### ISSUE TITLE
Wrong defined Items for properties

### ISSUE THREAD

**Issue by ReinhardWimmer** [BuildingSMART/IfcDoc#12]
Properties defined as P_Referencevalue always have the Item "IfcReal"
For example for Pset_BoilerPHistory, Property: Load:
- Value: IfcTimeSeries
- Item: IfcReal

The Item should be IfcPowerMeassure

Several other properties have the same issue.

**Comment by timchipman** [comment]
Fixed in V10.4 - UI has been restructured to allow selection of single secondary data type (rather than list as was previously used when enumerations were defined on properties directly)
