### ISSUE TITLE
Cannot define enumerated items for a property

### ISSUE THREAD

**Issue by ReinhardWimmer** [BuildingSMART/IfcDoc#13]
Properties defined as P_enumeratedvalue refer to a PEnum_...
Using the Penum_... as data type works, but adding the items defined in the PEnum does not work.

**Comment by timchipman** [comment]
Property enumeration constants can be added/removed/edited underneath the corresponding entry from the main tree view. In V10.4, the UI has been updated such that there is no longer a list for enumerations at a Property, and property enumerations are now organized separately from property sets.

**Comment by LaurensJN** [comment]
Related to this, it is not possible to add a property enum to a data schema. The button does not bring up any new item. 

![image](https://user-images.githubusercontent.com/23737460/107618685-4410c580-6c52-11eb-92cf-401394762a18.png)

It is possible, however, to add PropertyConstants to the main tree and add these to Property Enumerations in the main tree. Is there any way to add these to a data schema?
