### ISSUE TITLE
XSD export not functioning

### ISSUE THREAD

**Issue by afarello** [BuildingSMART/IfcDoc#17]
Hello,
it seems that some code like the following (copied from "FormatEXP.cs"):

string dirpath = System.IO.Path.GetDirectoryName(this.m_filename);

if (!System.IO.Directory.Exists(dirpath))
  {
  System.IO.Directory.CreateDirectory(dirpath);
  }

using (System.IO.StreamWriter writer = new System.IO.StreamWriter(this.m_filename))
  {
  if (writer.BaseStream.CanSeek)
    {
    writer.BaseStream.SetLength(0);
    }
writer.Write(content);
}

is needed in the "FormatXSD.cs" Save() method, after the instruction

string content = this.FormatDefinitions(this.m_project, map, this.m_included);

at line #104 to actually generate a file.

Best regards
Amedeo Farello

**Comment by afarello** [comment]
Could you please fix this? I gave you the solution.

**Comment by timchipman** [comment]
Thanks - to be included in version next week. Schedule has been rather full lately.

**Comment by timchipman** [comment]
Fixed in version 11.0
