### ISSUE TITLE
Cannot add attributes of type "IfcMassMeasure"

### ISSUE THREAD

**Issue by afarello** [BuildingSMART/IfcDoc#18]
The procedure to insert an attribute seems to be malfunctioning.
When I try to add an attribute of type "IfcMassMeasure" to an entity, I always end up with an item of type IfcAbsorbedDoseMeasure. Trying to change the type afterwards has no effect.

**Comment by timchipman** [comment]
Fixed in V10.8. Selecting a type-based data type in the alphabetical tab would not sync to the hierarchical tab (Previous workaround was to only select from hierarchical tab)
