### ISSUE TITLE
adding search functionality

### ISSUE THREAD

**Issue by yokoyamy** [BuildingSMART/IfcDoc#2]
Hi.

I tried to use IfcDOC for the purpose of understanding structure of IFC through a defining of MVD.

I thought It could be useful if IfcDOC has ‘find’or’search’ function.

Because for the person who hasn’t yet understood IFC well, it’s difficult to find classes what I need, and where they are placed.

And also it could be better if I can use ‘return’ or ‘historical back’ function after I jumped to some class diagram. I mean I can’t go back where I jumped from.

**Comment by timchipman** [comment]
This is now on the list of features to be added this quarter.

**Comment by yokoyamy** [comment]
Thank you. I’m looking forward to use it

**Comment by timchipman** [comment]
IfcDoc Version 9.5 (download now posted to buildingsmart-tech.org website) now contains this functionality for finding definitions and text.

**Comment by yokoyamy** [comment]
It is nice. It arrows me jump to where I look for and come-back easily.
Also, It will be more useful if I can find a class without scrolling after jumping. Some classes are out of scope of screen.  
Thank you.
