### ISSUE TITLE
OWL-generation

### ISSUE THREAD

**Issue by MichelBohms** [BuildingSMART/IfcDoc#26]
When I import  IFC4x1_RC3.xsd and try to publish an OWL schema I only get HTML as result, no IFC4x1_RC3.owl  (or better IFC4x1_RC3.rdf (the right extension), or even better IFC4x1_RC3.ttl.
Thanks for support how to make it work,
Michel

**Comment by timchipman** [comment]
Not sure if importing the XSD would contain everything needed to publish OWL, as XSD doesn't have enough structure to support a round trip from what is captured in .ifcdoc or EXPRESS schemas -- the import makes a lot of simplifying assumptions. Best bet would be to start with the .ifcdoc file for IFC4X1_RC3 and use that to generate OWL schemas.

**Comment by MichelBohms** [comment]
Ok!
So this is no alternative import too, I wait for the .ifcdoc!



Dr. ir. H.M. (Michel) Böhms
Data Scientist


T +31888663107
M +31630381220
E michel.bohms@tno.nl<mailto:michel.bohms@tno.nl>

Location<http://www.tno.nl/locaties/DTM>



[cid:image001.gif@01D274E0.2BE993B0]<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.
