### ISSUE TITLE
Reported format errors vary for different validation targets

### ISSUE THREAD

**Issue by hlg** [BuildingSMART/IfcDoc#28]
I am trying to validate an IFC file with IFCdoc version 11.5. For each validation target, I get different reports regarding format errors using the example file with 654 entity lines. For validation against the _Reference View_, there are 168 lines reported as faulty, for validation against _Design Transfer View_, these are only 71, and for validation against _General use_, there is none reported. I am not able to confirm any of these format errors with manual inspection. Is this intended behaviour or am I missing something?

**Comment by hlg** [comment]
I did some further investigation. The format errors report "Unknown type" for at most 14 entity types of the 77 types that appear in the file. Of these entity types, all instances seam to be reported as faulty. As said before, I checked some random sample lines, and can't confirm any format errors, spelling mistakes, wrong number or type of attributes. The remaining errors report "Collection contains invalid element", for entities that refer to these elements reported earlier to be of "Unknown type" in an aggregation attribute.

**Comment by hlg** [comment]
I think I found the reason for this behaviour. Does IfcDoc just report the format error "Unknown type" for all entity types that are not included in the MVD as concepts? If somebody can confirm this, then the issue can be closed. It is just misleading wording then ("format error").

**Comment by timchipman** [comment]
The report for "Unknown type" means that the file includes an instance of a type that it out of scope. It may very well be a valid IFC type, just not within scope of the Reference View or Design Transfer View (or whatever view was used). If any such error occurs, then there may be many downstream errors (e.g. collection contains invalid element).

If authoring custom model views, by default everything is opt-in (i.e. if you don't specify use of an object type directly or indirectly then it is out of scope) - though a view can also be configured to include all IFC types (nothing filtered out).

**Comment by hlg** [comment]
Thank you for clarification, that is what I guessed after some thinking. The wording could be improved though.

**Comment by hlg** [comment]
I was assuming that these "format errors" are reported as a result of proper validation against the schema or a subschema defined by the MVD. But as it turns out, there seems to be only minimal syntactic validation and no schema-level validation. Neither the number of attributes, the types of attributes nor the presence of mandatory attribute values is checked and reported in case of failure. Is this by intention?

**Comment by timchipman** [comment]
Yes, the wording and documentation should be improved for that. The scope of checking is limited to MVD-based rules for what data should be included, and only minimal syntax checking for purposes of loading the data. For validation of EXPRESS rules, there are other tools for that at gtds.buildingsmart.org.
