### ISSUE TITLE
IfcDoc Express schema

### ISSUE THREAD

**Issue by ifcwebserver** [buildingSMART/IfcDoc#3]
IfcDoc saves and exports MVD definitions and IFC documentation as *.ifcdoc files using ISO 10303-21, STEP  Physical File.
I would like to parse this files but I was not able to find the EXPRESS schema file anywhere. 

Is it possible to publish the schema behind IfcDoc tool as EXPRESS file?

**Comment by timchipman** [comment]
An EXPRESS file has never been created for the .ifcdoc schema, though it probably wouldn't be too much effort to derive it: the file at https://github.com/BuildingSMART/IfcDoc/blob/master/SchemaDoc.cs reflects the schema, where any field marked with the DataMember attribute indicates the order it is serialized for STEP (following any fields from the supertype).

That said, the .ifcdoc schema is more of a container that encompasses various other schemas, and so far there hasn't been any intention to put it forward as any official documented format, as is done with EXPRESS, mvdXML, IFC property set templates, etc. The .ifcdoc schema has gone through many incremental expansions to support added functionality (though it has been more stable recently), whereas the other file formats are frozen.

In addition to exporting specific formats, IfcDoc also has an option to save everything as an Access database, which would be another option for getting at all the data.

Is there particular information you need that isn't captured by the other documented formats?

**Comment by ifcwebserver** [comment]
Thanks a lot for the quick and detailed answer.

I was justing wondering if parsing ifcdoc files using an EXPRESS parser would be easier in order to extract information about IFC schema, Psets, QTO, MVDs without the need to deal with few other formats like mvdXML,HTML, Pset as XML, etc.

Maybe  I will give it later a try to extract the EXPRESS schema from the source code

**Comment by timchipman** [comment]
With latest checkin (IfcDoc V12.0) it's now possible to generate EXPRESS schema from what is encoded in .ifcdoc files. Use File - Import - .exe; pick ifcdoc.exe, which will import all public data types. Then delete all namespaces except for BuildingSmart.Schema.Doc, then export as .exp file.

**Comment by timchipman** [comment]
(*
Copyright by:
buildingSMART International Limited, 1996-2018

Any technical documentation made available by buildingSMART International Limited
is the copyrighted work of buildingSMART International Limited and is owned by the 
buildingSMART International Limited. It may be photocopied, used in software development, 
or translated into another computer language without prior written consent from 
buildingSMART International Limited provided that full attribution is given. 
Prior written consent is required if changes are made to the technical specification.

This material is delivered to you as is and buildingSMART International Limited makes 
no warranty of any kind with regard to it, including, but not limited to, the implied 
warranties as to its accuracy or fitness for a particular purpose. Any use of the 
technical documentation or the information contained therein is at the risk of the user. 
Documentation may include technical or other inaccuracies or typographical errors. 
buildingSMART International Limited shall not be liable for errors contained therein or 
for incidental consequential damages in connection with the furnishing, performance or use 
of the material. The information contained in this document is subject to change without notice.

Issue date:
Sunday, July 1, 2018

*)

SCHEMA UNSPECIFIEDSCHEMA;

TYPE DiagramFormat = ENUMERATION OF
	(ExpressG
	,UML);
END_TYPE;

TYPE DocAggregationEnum = ENUMERATION OF
	(NONE
	,LIST
	,ARRAY
	,SET
	,BAG);
END_TYPE;

TYPE DocCategoryEnum = ENUMERATION OF
	(Definition
	,Agreement
	,Diagram
	,Instantiation
	,Example);
END_TYPE;

TYPE DocChangeActionEnum = ENUMERATION OF
	(NOCHANGE
	,ADDED
	,DELETED
	,MODIFIED
	,MOVED);
END_TYPE;

TYPE DocChangeAspectEnum = ENUMERATION OF
	(NAME
	,TYPE
	,INSTANTIATION
	,AGGREGATION
	,SCHEMA
	,XSDFORMAT
	,XSDTAGLESS
	,STATUS);
END_TYPE;

TYPE DocCodeEnum = ENUMERATION OF
	(Default
	,Entities
	,Attributes
	,Rules
	,Functions
	,Documentation
	,Localization
	,Diagrams
	,Views
	,Examples
	,All);
END_TYPE;

TYPE DocDefinitionScopeEnum = ENUMERATION OF
	(None
	,Type
	,TypeConstant
	,Entity
	,EntityAttribute
	,Rule
	,RuleWhere
	,Pset
	,PsetProperty
	,PEnum
	,PEnumConstant
	,Qset
	,QsetQuantity
	,Default);
END_TYPE;

TYPE DocExchangeApplicabilityEnum = ENUMERATION OF
	(Export
	,Import);
END_TYPE;

TYPE DocExchangeRequirementEnum = ENUMERATION OF
	(Mandatory
	,Optional
	,NotRelevant
	,NotRecommended
	,Excluded);
END_TYPE;

TYPE DocExpressType = ENUMERATION OF
	(OBJECT
	,BOOLEAN
	,LOGICAL
	,INTEGER
	,REAL
	,NUMBER
	,STRING
	,BINARY);
END_TYPE;

TYPE DocFormatOptionEnum = ENUMERATION OF
	(None
	,Schema
	,Examples
	,Markup);
END_TYPE;

TYPE DocFormatSchemaEnum = ENUMERATION OF
	(XML
	,STEP
	,SQL
	,OWL
	,JSON
	,CS);
END_TYPE;

TYPE DocMetricEnum = ENUMERATION OF
	(Value
	,Size
	,Type
	,Unique
	,Exists);
END_TYPE;

TYPE DocOpCode = ENUMERATION OF
	(NoOperation
	,CompareEqual
	,CompareGreaterThan
	,CompareGreaterThanOrEqual
	,CompareLessThan
	,CompareLessThanOrEqual
	,CompareNotEqual
	,And
	,Or
	,Xor
	,LoadString
	,LoadLength
	,IsInstance
	,LoadArgument
	,LoadField
	,IsIncluded
	,IsUnique);
END_TYPE;

TYPE DocOperatorEnum = ENUMERATION OF
	(EQUAL
	,NOT_EQUAL
	,GREATER_THAN
	,GREATER_THAN_OR_EQUAL
	,LESS_THAN
	,LESS_THAN_OR_EQUAL);
END_TYPE;

TYPE DocPropertyTemplateTypeEnum = ENUMERATION OF
	(P_SINGLEVALUE
	,P_ENUMERATEDVALUE
	,P_BOUNDEDVALUE
	,P_LISTVALUE
	,P_TABLEVALUE
	,P_REFERENCEVALUE
	,COMPLEX);
END_TYPE;

TYPE DocQuantityTemplateTypeEnum = ENUMERATION OF
	(Q_LENGTH
	,Q_AREA
	,Q_VOLUME
	,Q_COUNT
	,Q_WEIGHT
	,Q_TIME);
END_TYPE;

TYPE DocStateEnum = ENUMERATION OF
	(READWRITE
	,READONLY
	,LOCKED
	,READWRITELOCKED
	,READONLYLOCKED);
END_TYPE;

TYPE DocTemplateOperator = ENUMERATION OF
	(And
	,Or
	,Not
	,Nand
	,Nor
	,Xor
	,Nxor);
END_TYPE;

TYPE DocXsdFormatEnum = ENUMERATION OF
	(Default
	,Hidden
	,Attribute
	,Element
	,Content
	,Type
	,Simple);
END_TYPE;

TYPE IDocTreeHost = SELECT
	(DocDefinitionRef
	,DocEntity
	,DocSelect);
END_TYPE;

TYPE IDocumentation = SELECT
	(DocAbbreviation
	,DocAnnex
	,DocAnnotation
	,DocAttribute
	,DocAttributeRef
	,DocChangeAction
	,DocChangeSet
	,DocComment
	,DocConceptRoot
	,DocConstant
	,DocConstraint
	,DocDefined
	,DocDefinition
	,DocDefinitionRef
	,DocEntity
	,DocEnumeration
	,DocExample
	,DocExchangeDefinition
	,DocFunction
	,DocGlobalRule
	,DocLocalization
	,DocModelView
	,DocObject
	,DocPageSource
	,DocPageTarget
	,DocParameter
	,DocPrimitive
	,DocProcess
	,DocProperty
	,DocPropertyConstant
	,DocPropertyEnumeration
	,DocPropertySet
	,DocPublication
	,DocQuantity
	,DocQuantitySet
	,DocReference
	,DocSchema
	,DocSchemaRef
	,DocSection
	,DocSelect
	,DocSelectItem
	,DocSubtype
	,DocTemplateDefinition
	,DocTemplateItem
	,DocTemplateUsage
	,DocTerm
	,DocType
	,DocUniqueRule
	,DocUniqueRuleItem
	,DocVariableSet
	,DocWhereRule);
END_TYPE;

TYPE IFormatExtension = SELECT
);
END_TYPE;

ENTITY DocAbbreviation
 SUBTYPE OF (DocObject);
END_ENTITY;

ENTITY DocAnnex
 SUBTYPE OF (DocObject);
END_ENTITY;

ENTITY DocAnnotation
 SUBTYPE OF (DocObject);
	Annotations : OPTIONAL LIST [0:?] OF DocAnnotation;
END_ENTITY;

ENTITY DocAttribute
 SUBTYPE OF (DocObject);
	DefinedType : OPTIONAL STRING;
	Definition : OPTIONAL DocDefinition;
	AttributeFlags : OPTIONAL INTEGER;
	AggregationType : OPTIONAL INTEGER;
	AggregationFlag : OPTIONAL INTEGER;
	AggregationLower : OPTIONAL STRING;
	AggregationUpper : OPTIONAL STRING;
	Inverse : OPTIONAL STRING;
	Derived : OPTIONAL STRING;
	AggregationAttribute : OPTIONAL DocAttribute;
	DiagramLine : OPTIONAL LIST [0:?] OF DocPoint;
	DiagramLabel : OPTIONAL DocRectangle;
	XsdFormat : OPTIONAL DocXsdFormatEnum;
	XsdTagless : OPTIONAL BOOLEAN;
END_ENTITY;

ENTITY DocAttributeRef
 SUBTYPE OF (DocObject);
	Attribute : OPTIONAL DocAttribute;
	DefinitionRef : OPTIONAL DocDefinitionRef;
	DiagramLine : OPTIONAL LIST [0:?] OF DocPoint;
END_ENTITY;

ENTITY DocChangeAction
 SUBTYPE OF (DocObject);
	Action : OPTIONAL DocChangeActionEnum;
	Aspects : OPTIONAL LIST [0:?] OF DocChangeAspect;
	Changes : OPTIONAL LIST [0:?] OF DocChangeAction;
	ImpactSPF : OPTIONAL BOOLEAN;
	ImpactXML : OPTIONAL BOOLEAN;
END_ENTITY;

ENTITY DocChangeAspect;
	Aspect : OPTIONAL DocChangeAspectEnum;
	OldValue : OPTIONAL STRING;
	NewValue : OPTIONAL STRING;
END_ENTITY;

ENTITY DocChangeSet
 SUBTYPE OF (DocObject);
	ChangesEntities : OPTIONAL LIST [0:?] OF DocChangeAction;
	VersionCompared : OPTIONAL STRING;
	VersionBaseline : OPTIONAL STRING;
	ChangesProperties : OPTIONAL LIST [0:?] OF DocChangeAction;
	ChangesQuantities : OPTIONAL LIST [0:?] OF DocChangeAction;
	ChangesViews : OPTIONAL LIST [0:?] OF DocChangeAction;
END_ENTITY;

ENTITY DocComment
 SUBTYPE OF (DocDefinition);
END_ENTITY;

ENTITY DocConceptRoot
 SUBTYPE OF (DocObject);
	ApplicableEntity : OPTIONAL DocEntity;
	Concepts : OPTIONAL LIST [0:?] OF DocTemplateUsage;
	ApplicableTemplate : OPTIONAL DocTemplateDefinition;
	ApplicableItems : OPTIONAL LIST [0:?] OF DocTemplateItem;
	ApplicableOperator : OPTIONAL DocTemplateOperator;
END_ENTITY;

ENTITY DocConstant
 SUBTYPE OF (DocObject);
END_ENTITY;

ENTITY DocConstraint
 SUPERTYPE OF (ONEOF
    (DocFunction
    ,DocGlobalRule
    ,DocUniqueRule
    ,DocWhereRule))
 SUBTYPE OF (DocObject);
	Expression : OPTIONAL STRING;
END_ENTITY;

ENTITY DocDefined
 SUBTYPE OF (DocType);
	DefinedType : OPTIONAL STRING;
	Definition : OPTIONAL DocDefinition;
	WhereRules : OPTIONAL LIST [0:?] OF DocWhereRule;
	Length : OPTIONAL INTEGER;
	Aggregation : OPTIONAL DocAttribute;
	DiagramLine : OPTIONAL LIST [0:?] OF DocPoint;
END_ENTITY;

ENTITY DocDefinition
 SUPERTYPE OF (ONEOF
    (DocComment
    ,DocDefinitionRef
    ,DocEntity
    ,DocPageSource
    ,DocPageTarget
    ,DocPrimitive
    ,DocType))
 SUBTYPE OF (DocObject);
	DiagramRectangle : OPTIONAL DocRectangle;
	DiagramNumber : OPTIONAL INTEGER;
END_ENTITY;

ENTITY DocDefinitionRef
 SUBTYPE OF (DocDefinition);
	Tree : OPTIONAL LIST [0:?] OF DocLine;
	AttributeRefs : OPTIONAL LIST [0:?] OF DocAttributeRef;
END_ENTITY;

ENTITY DocEntity
 SUBTYPE OF (DocDefinition);
	BaseDefinition : OPTIONAL STRING;
	EntityFlags : OPTIONAL INTEGER;
	Subtypes : OPTIONAL LIST [0:?] OF DocSubtype;
	Attributes : OPTIONAL LIST [0:?] OF DocAttribute;
	UniqueRules : OPTIONAL LIST [0:?] OF DocUniqueRule;
	WhereRules : OPTIONAL LIST [0:?] OF DocWhereRule;
	Tree : OPTIONAL LIST [0:?] OF DocLine;
END_ENTITY;

ENTITY DocEnumeration
 SUBTYPE OF (DocType);
	Constants : OPTIONAL LIST [0:?] OF DocConstant;
END_ENTITY;

ENTITY DocExample
 SUBTYPE OF (DocVariableSet);
	Examples : OPTIONAL LIST [0:?] OF DocExample;
	ApplicableTemplates : OPTIONAL LIST [0:?] OF DocTemplateDefinition;
	ModelView : OPTIONAL DocModelView;
	File : OPTIONAL BINARY;
	Views : OPTIONAL LIST [0:?] OF DocModelView;
	Path : OPTIONAL STRING;
END_ENTITY;

ENTITY DocExchangeDefinition
 SUBTYPE OF (DocObject);
	Icon : OPTIONAL BINARY;
	Applicability : OPTIONAL DocExchangeApplicabilityEnum;
	ExchangeClass : OPTIONAL STRING;
	SenderClass : OPTIONAL STRING;
	ReceiverClass : OPTIONAL STRING;
END_ENTITY;

ENTITY DocExchangeItem;
	Exchange : OPTIONAL DocExchangeDefinition;
	Applicability : OPTIONAL DocExchangeApplicabilityEnum;
	Requirement : OPTIONAL DocExchangeRequirementEnum;
END_ENTITY;

ENTITY DocExpression;
	Name : OPTIONAL STRING;
	Metric : OPTIONAL DocMetricEnum;
	Operator : OPTIONAL DocOperatorEnum;
	Value : OPTIONAL STRING;
END_ENTITY;

ENTITY DocFindResult;
END_ENTITY;

ENTITY DocFormat;
	FormatType : OPTIONAL DocFormatSchemaEnum;
	FormatOptions : OPTIONAL DocFormatOptionEnum;
END_ENTITY;

ENTITY DocFunction
 SUBTYPE OF (DocConstraint);
	Parameters : OPTIONAL LIST [0:?] OF DocParameter;
	ReturnValue : OPTIONAL STRING;
END_ENTITY;

ENTITY DocGeometry
 SUPERTYPE OF (ONEOF
    (DocPoint
    ,DocRectangle));
END_ENTITY;

ENTITY DocGlobalRule
 SUBTYPE OF (DocConstraint);
	WhereRules : OPTIONAL LIST [0:?] OF DocWhereRule;
	ApplicableEntity : OPTIONAL STRING;
END_ENTITY;

ENTITY DocLine;
	DiagramLine : OPTIONAL LIST [0:?] OF DocPoint;
	Tree : OPTIONAL LIST [0:?] OF DocLine;
	Definition : OPTIONAL DocDefinition;
END_ENTITY;

ENTITY DocLocalization;
	Locale : OPTIONAL STRING;
	Category : OPTIONAL DocCategoryEnum;
	Name : OPTIONAL STRING;
	Documentation : OPTIONAL STRING;
	URL : OPTIONAL STRING;
END_ENTITY;

ENTITY DocModelRule
 SUPERTYPE OF (ONEOF
    (DocModelRuleAttribute
    ,DocModelRuleConstraint
    ,DocModelRuleEntity));
	Name : OPTIONAL STRING;
	Description : OPTIONAL STRING;
	Identification : OPTIONAL STRING;
	Rules : OPTIONAL LIST [0:?] OF DocModelRule;
	CardinalityMin : OPTIONAL INTEGER;
	CardinalityMax : OPTIONAL INTEGER;
 INVERSE
	ParentRule : DocModelRule FOR Rules;
END_ENTITY;

ENTITY DocModelRuleAttribute
 SUBTYPE OF (DocModelRule);
END_ENTITY;

ENTITY DocModelRuleConstraint
 SUBTYPE OF (DocModelRule);
	Expression : OPTIONAL DocOpExpression;
END_ENTITY;

ENTITY DocModelRuleEntity
 SUBTYPE OF (DocModelRule);
	References : OPTIONAL LIST [0:?] OF DocTemplateDefinition;
	Prefix : OPTIONAL STRING;
END_ENTITY;

ENTITY DocModelView
 SUBTYPE OF (DocObject);
	Exchanges : OPTIONAL LIST [0:?] OF DocExchangeDefinition;
	ConceptRoots : OPTIONAL LIST [0:?] OF DocConceptRoot;
	BaseView : OPTIONAL STRING;
	XsdUri : OPTIONAL STRING;
	XsdFormats : OPTIONAL LIST [0:?] OF DocXsdFormat;
	IncludeAllDefinitions : OPTIONAL BOOLEAN;
	RootEntity : OPTIONAL STRING;
	Icon : OPTIONAL BINARY;
	Processes : OPTIONAL LIST [0:?] OF DocProcess;
	ModelViews : OPTIONAL LIST [0:?] OF DocModelView;
END_ENTITY;

ENTITY DocObject
 SUPERTYPE OF (ONEOF
    (DocAbbreviation
    ,DocAnnex
    ,DocAnnotation
    ,DocAttribute
    ,DocAttributeRef
    ,DocChangeAction
    ,DocChangeSet
    ,DocConceptRoot
    ,DocConstant
    ,DocConstraint
    ,DocDefinition
    ,DocExchangeDefinition
    ,DocModelView
    ,DocParameter
    ,DocProcess
    ,DocProperty
    ,DocPropertyConstant
    ,DocPropertyEnumeration
    ,DocPublication
    ,DocQuantity
    ,DocReference
    ,DocSchema
    ,DocSchemaRef
    ,DocSection
    ,DocSelectItem
    ,DocSubtype
    ,DocTemplateDefinition
    ,DocTemplateItem
    ,DocTemplateUsage
    ,DocTerm
    ,DocUniqueRuleItem
    ,DocVariableSet));
	Name : OPTIONAL STRING;
	Documentation : OPTIONAL STRING;
	UniqueId : OPTIONAL STRING;
	Code : OPTIONAL STRING;
	Version : OPTIONAL STRING;
	Status : OPTIONAL STRING;
	Author : OPTIONAL STRING;
	Owner : OPTIONAL STRING;
	Copyright : OPTIONAL STRING;
	Localization : OPTIONAL LIST [0:?] OF DocLocalization;
END_ENTITY;

ENTITY DocOp
 SUPERTYPE OF (ONEOF
    (DocOpExpression
    ,DocOpValue));
	Operation : OPTIONAL DocOpCode;
END_ENTITY;

ENTITY DocOpExpression
 SUPERTYPE OF (ONEOF
    (DocOpLogical
    ,DocOpStatement))
 SUBTYPE OF (DocOp);
END_ENTITY;

ENTITY DocOpLiteral
 SUBTYPE OF (DocOpValue);
	Literal : OPTIONAL STRING;
END_ENTITY;

ENTITY DocOpLogical
 SUBTYPE OF (DocOpExpression);
	ExpressionA : OPTIONAL DocOpExpression;
	ExpressionB : OPTIONAL DocOpExpression;
END_ENTITY;

ENTITY DocOpParameter
 SUBTYPE OF (DocOpValue);
	AttributeRule : OPTIONAL DocModelRuleAttribute;
END_ENTITY;

ENTITY DocOpReference
 SUBTYPE OF (DocOpValue);
	EntityRule : OPTIONAL DocModelRuleEntity;
END_ENTITY;

ENTITY DocOpStatement
 SUBTYPE OF (DocOpExpression);
	Reference : OPTIONAL DocOpReference;
	Value : OPTIONAL DocOpValue;
	Metric : OPTIONAL DocOpCode;
END_ENTITY;

ENTITY DocOpValue
 SUPERTYPE OF (ONEOF
    (DocOpLiteral
    ,DocOpParameter
    ,DocOpReference))
 SUBTYPE OF (DocOp);
END_ENTITY;

ENTITY DocPageSource
 SUBTYPE OF (DocDefinition);
END_ENTITY;

ENTITY DocPageTarget
 SUBTYPE OF (DocDefinition);
	DiagramLine : OPTIONAL LIST [0:?] OF DocPoint;
	Sources : OPTIONAL LIST [0:?] OF DocPageSource;
	Definition : OPTIONAL DocDefinition;
END_ENTITY;

ENTITY DocParameter
 SUBTYPE OF (DocObject);
	DefinedType : OPTIONAL STRING;
END_ENTITY;

ENTITY DocPoint
 SUBTYPE OF (DocGeometry);
	X : OPTIONAL REAL;
	Y : OPTIONAL REAL;
END_ENTITY;

ENTITY DocPrimitive
 SUBTYPE OF (DocDefinition);
END_ENTITY;

ENTITY DocProcess
 SUBTYPE OF (DocObject);
	Inputs : OPTIONAL LIST [0:?] OF DocExchangeItem;
	Outputs : OPTIONAL LIST [0:?] OF DocExchangeItem;
END_ENTITY;

ENTITY DocProject;
	Sections : OPTIONAL LIST [0:?] OF DocSection;
	Annexes : OPTIONAL LIST [0:?] OF DocAnnex;
	Templates : OPTIONAL LIST [0:?] OF DocTemplateDefinition;
	ModelViews : OPTIONAL LIST [0:?] OF DocModelView;
	ChangeSets : OPTIONAL LIST [0:?] OF DocChangeSet;
	Examples : OPTIONAL LIST [0:?] OF DocExample;
	NormativeReferences : OPTIONAL LIST [0:?] OF DocReference;
	InformativeReferences : OPTIONAL LIST [0:?] OF DocReference;
	Terms : OPTIONAL LIST [0:?] OF DocTerm;
	Abbreviations : OPTIONAL LIST [0:?] OF DocAbbreviation;
	Annotations : OPTIONAL LIST [0:?] OF DocAnnotation;
	Publications : OPTIONAL LIST [0:?] OF DocPublication;
END_ENTITY;

ENTITY DocProperty
 SUBTYPE OF (DocObject);
	PropertyType : OPTIONAL DocPropertyTemplateTypeEnum;
	PrimaryDataType : OPTIONAL STRING;
	SecondaryDataType : OPTIONAL STRING;
	Elements : OPTIONAL LIST [0:?] OF DocProperty;
	AccessState : OPTIONAL DocStateEnum;
END_ENTITY;

ENTITY DocPropertyConstant
 SUBTYPE OF (DocObject);
END_ENTITY;

ENTITY DocPropertyEnumeration
 SUBTYPE OF (DocObject);
	Constants : OPTIONAL LIST [0:?] OF DocPropertyConstant;
END_ENTITY;

ENTITY DocPropertySet
 SUBTYPE OF (DocVariableSet);
	PropertySetType : OPTIONAL STRING;
	Properties : OPTIONAL LIST [0:?] OF DocProperty;
END_ENTITY;

ENTITY DocPublication
 SUBTYPE OF (DocObject);
	Views : OPTIONAL LIST [0:?] OF DocModelView;
	Formats : OPTIONAL LIST [0:?] OF DocFormat;
	ChangeSets : OPTIONAL LIST [0:?] OF DocChangeSet;
	Annotations : OPTIONAL LIST [0:?] OF DocAnnotation;
	Header : OPTIONAL STRING;
	Footer : OPTIONAL STRING;
	HideHistory : OPTIONAL BOOLEAN;
	ISO : OPTIONAL BOOLEAN;
	UML : OPTIONAL BOOLEAN;
	Comparison : OPTIONAL BOOLEAN;
	Exchanges : OPTIONAL BOOLEAN;
	HtmlExamples : OPTIONAL BOOLEAN;
	ReportIssues : OPTIONAL BOOLEAN;
END_ENTITY;

ENTITY DocQuantity
 SUBTYPE OF (DocObject);
	QuantityType : OPTIONAL DocQuantityTemplateTypeEnum;
	AccessState : OPTIONAL DocStateEnum;
END_ENTITY;

ENTITY DocQuantitySet
 SUBTYPE OF (DocVariableSet);
	Quantities : OPTIONAL LIST [0:?] OF DocQuantity;
END_ENTITY;

ENTITY DocRectangle
 SUBTYPE OF (DocGeometry);
	X : OPTIONAL REAL;
	Y : OPTIONAL REAL;
	Width : OPTIONAL REAL;
	Height : OPTIONAL REAL;
END_ENTITY;

ENTITY DocReference
 SUBTYPE OF (DocObject);
END_ENTITY;

ENTITY DocSchema
 SUBTYPE OF (DocObject);
	Annotations : OPTIONAL LIST [0:?] OF DocAnnotation;
	Types : OPTIONAL LIST [0:?] OF DocType;
	Entities : OPTIONAL LIST [0:?] OF DocEntity;
	Functions : OPTIONAL LIST [0:?] OF DocFunction;
	GlobalRules : OPTIONAL LIST [0:?] OF DocGlobalRule;
	PropertySets : OPTIONAL LIST [0:?] OF DocPropertySet;
	QuantitySets : OPTIONAL LIST [0:?] OF DocQuantitySet;
	PageTargets : OPTIONAL LIST [0:?] OF DocPageTarget;
	SchemaRefs : OPTIONAL LIST [0:?] OF DocSchemaRef;
	Comments : OPTIONAL LIST [0:?] OF DocComment;
	PropertyEnums : OPTIONAL LIST [0:?] OF DocPropertyEnumeration;
	Primitives : OPTIONAL LIST [0:?] OF DocPrimitive;
	DiagramPagesHorz : OPTIONAL INTEGER;
	DiagramPagesVert : OPTIONAL INTEGER;
END_ENTITY;

ENTITY DocSchemaRef
 SUBTYPE OF (DocObject);
	Definitions : OPTIONAL LIST [0:?] OF DocDefinitionRef;
END_ENTITY;

ENTITY DocSection
 SUBTYPE OF (DocObject);
	Annotations : OPTIONAL LIST [0:?] OF DocAnnotation;
	Schemas : OPTIONAL LIST [0:?] OF DocSchema;
END_ENTITY;

ENTITY DocSelect
 SUBTYPE OF (DocType);
	Selects : OPTIONAL LIST [0:?] OF DocSelectItem;
	Tree : OPTIONAL LIST [0:?] OF DocLine;
END_ENTITY;

ENTITY DocSelectItem
 SUBTYPE OF (DocObject);
END_ENTITY;

ENTITY DocSubtype
 SUBTYPE OF (DocObject);
	DefinedType : OPTIONAL STRING;
END_ENTITY;

ENTITY DocTemplateDefinition
 SUBTYPE OF (DocObject);
	Type : OPTIONAL STRING;
	Rules : OPTIONAL LIST [0:?] OF DocModelRule;
	Templates : OPTIONAL LIST [0:?] OF DocTemplateDefinition;
	IsDisabled : OPTIONAL BOOLEAN;
END_ENTITY;

ENTITY DocTemplateItem
 SUBTYPE OF (DocObject);
	Concepts : OPTIONAL LIST [0:?] OF DocTemplateUsage;
	Optional : OPTIONAL BOOLEAN;
	Reference : OPTIONAL BOOLEAN;
	Key : OPTIONAL BOOLEAN;
	Calculated : OPTIONAL BOOLEAN;
	RuleInstanceID : OPTIONAL STRING;
	RuleParameters : OPTIONAL STRING;
	Order : OPTIONAL INTEGER;
	Exchanges : OPTIONAL LIST [0:?] OF DocExchangeItem;
END_ENTITY;

ENTITY DocTemplateUsage
 SUBTYPE OF (DocObject);
	Definition : OPTIONAL DocTemplateDefinition;
	Items : OPTIONAL LIST [0:?] OF DocTemplateItem;
	Exchanges : OPTIONAL LIST [0:?] OF DocExchangeItem;
	Override : OPTIONAL BOOLEAN;
	Suppress : OPTIONAL BOOLEAN;
	Concepts : OPTIONAL LIST [0:?] OF DocTemplateUsage;
	Operator : OPTIONAL DocTemplateOperator;
END_ENTITY;

ENTITY DocTerm
 SUBTYPE OF (DocObject);
	Terms : OPTIONAL LIST [0:?] OF DocTerm;
END_ENTITY;

ENTITY DocType
 SUPERTYPE OF (ONEOF
    (DocDefined
    ,DocEnumeration
    ,DocSelect))
 SUBTYPE OF (DocDefinition);
END_ENTITY;

ENTITY DocUniqueRule
 SUBTYPE OF (DocConstraint);
	Items : OPTIONAL LIST [0:?] OF DocUniqueRuleItem;
END_ENTITY;

ENTITY DocUniqueRuleItem
 SUBTYPE OF (DocObject);
END_ENTITY;

ENTITY DocVariableSet
 SUPERTYPE OF (ONEOF
    (DocExample
    ,DocPropertySet
    ,DocQuantitySet))
 SUBTYPE OF (DocObject);
	ApplicableType : OPTIONAL STRING;
END_ENTITY;

ENTITY DocWhereRule
 SUBTYPE OF (DocConstraint);
END_ENTITY;

ENTITY DocXsdFormat;
	Entity : OPTIONAL STRING;
	Attribute : OPTIONAL STRING;
	XsdFormat : OPTIONAL DocXsdFormatEnum;
	XsdTagless : OPTIONAL BOOLEAN;
END_ENTITY;

ENTITY SchemaDOC;
END_ENTITY;

END_SCHEMA;

**Comment by timchipman** [comment]
Generated EXPRESS schema copied above.
