### ISSUE TITLE
Path to .ifcdoc file

### ISSUE THREAD

**Issue by klacol** [BuildingSMART/IfcDoc#31]
Hello,

on this page we can download the last version of the IfcDoc-Files:
http://www.buildingsmart-tech.org/specifications/specification-tools/ifcdoc-tool/ifcdoc-baselines

Is the last version (not released) of this file also available in ths GitHub Repository?

**Comment by klacol** [comment]
Hi Tim,
(now I  missed the notification.)

Thanks for the explanation. So you migrate the underlying storage format of IfcDoc to another format. How do you plan the workflow then for pull requests? Would I open the schema in IfcDoc and correct within IfcDoc (let's say) a corrected typo in a description? And then save, commit and PR. All based on an issue?

**Comment by timchipman** [comment]
You can make changes with whatever tool used for editing files on GitHub -- while IfcDoc can still be used, for some simple documentation change, it might be quicker to edit the specific HTML file and commit it.

**Comment by klacol** [comment]
Hi Tim, 

I do not really understand this. Let's say, I want to prepare and contribute a PR to fix this issue:

http://jira.buildingsmart.org/browse/IFR-1172

What would be the best process in your opinion? In which file could I fix this?

**Comment by timchipman** [comment]
For descriptions of fields and enumeration constants, those are defined directly in code (plain text, not HTML) for English. So for the specific issue referenced, you would edit this file here:

https://github.com/BuildingSMART/IfcDoc/blob/master/IfcKit/schemas/IFC4/IfcBuildingControlsDomain/IfcSensorTypeEnum.cs

**Comment by klacol** [comment]
Ok, that is clear now. I will work on this in the issue #32 .

**Comment by klacol** [comment]
Ok, this is now clear
