### ISSUE TITLE
IfcSensorTypeEnum.RADIATIONSENSOR has wrong description [IFR-1172]

### ISSUE THREAD

**Issue by klacol** [BuildingSMART/IfcDoc#32]
The description of IfcSensorTypeEnum.RADIATIONSENSOR is 
"A device that senses or detects pressure."

The description should be changed to 
"A device that senses or detects radiation."

This issue was transfered from
http://jira.buildingsmart.org/browse/IFR-1172

**Comment by klacol** [comment]
Ok, great. What about other versions of IFC? Do I have to file separate issues per IFC schema version?

http://www.buildingsmart-tech.org/ifc (Tab "Schemas")

**Comment by jwouellette** [comment]
"Mainline" should always contain all changes (IFC2x).

"Release Branches" (IFC2x3, IFC4, IFC4.1) should contain changes only while
they are "open". After publishing (IFC4.1), they should be closed to
changes.

In addition, there should be an agreement or policy on releases... that is,
will there be a 4.3? a 4.5? a 4.9" if so, when? what is the release cycle?
That way, the project can be spit up into other parallel/concurrent
branches within the same "trunk" - IFC4 > IFC4.1 > IFC4.2 > IFC4.3 >
IFC4.4... Each concurrent development branch must sync to the others, but
stops syncing when it is "published". This will take some further planning
and management.

Changes should always go "up" to Mainline, but never "back" to previous
published releases. However, changes should always go "forward" or
"sideways" to other release/development branches within the same .

This allows people to branch mainline for very experimental future
development and pull changes that have been made in the previous release
cycle, but don't affect the current one.

**Comment by klacol** [comment]
I think, the release- and version management is a topic for one or more separate issue(s). We should disuss it there. I should have opened a second issue for that.

**Comment by klacol** [comment]
Tim has now committet the correction from pull request #33  to the master branch
https://github.com/BuildingSMART/IfcDoc/commit/569f10785d1cfe6e48611ddf5ad5cc7d7bf06d73

So I close this issue now. I think it is best practice in the first step to contribute to the master branch and contribute things for future releases. The workflow, how to contribute (and deploy) to existing releases, must be clarified.
